#!/usr/bin/env python3
"""Generate the internals Go package reference from `go doc` output."""

from __future__ import annotations

import pathlib
import subprocess


ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "internals" / "go-package-reference.md"

PACKAGES = [
    ("API types", ["go", "doc", "-all", "./api/v1alpha1"]),
    ("Metadata helpers", ["go", "doc", "-all", "./pkg/metadata"]),
    ("Operator internals", ["go", "doc", "-all", "./internal/operator"]),
    ("CLI internals", ["go", "doc", "-all", "./internal/cli"]),
    ("CLI binary", ["go", "doc", "-cmd", "./cmd/mcp-runtime"]),
    ("Operator binary", ["go", "doc", "-cmd", "./cmd/operator"]),
]


def run(command: list[str]) -> str:
    return subprocess.check_output(command, cwd=ROOT, text=True)


def main() -> None:
    chunks = [
        "# Go Package Reference",
        "",
        "<!-- Generated by docs/scripts/generate_go_package_reference.py; do not edit by hand. -->",
        "",
        "This page captures `go doc` output for the main contributor-facing Go packages.",
        "Regenerate it from the repository root with:",
        "",
        "```bash",
        "python3 docs/scripts/generate_go_package_reference.py",
        "```",
        "",
    ]

    for title, command in PACKAGES:
        chunks.extend(
            [
                f"## {title}",
                "",
                "Command:",
                "",
                "```bash",
                " ".join(command),
                "```",
                "",
                "```text",
                run(command).rstrip(),
                "```",
                "",
            ]
        )

    OUT.write_text("\n".join(chunks), encoding="utf-8")


if __name__ == "__main__":
    main()
